### ISSUE TITLE
Wishlist: add tags to connection metadata record creation.

### ISSUE THREAD

**Issue by burdettadam** [sicpa-dlab/aries-cloudagent-python#49]
Story: As a developer, I would like to be able to search metadata records with a wallet query language. 
details: currently you can pass metadata value into create connection invitation. the resulting metadata record will have two tags 
```
"connection_id": "<a connection_id>",
"key": "<key of the key value passed in>"
```
if create a connection invitation allowed a way to pass metadata tags as a parameter, these tags could be used for metadata record creation allowing future searching with wallet query language.

The goal is to make it easier to retrieve connections based on metadata associated with it.

**Comment by Luis-GA** [comment]
Developed here: https://github.com/sicpa-dlab/aries-cloudagent-python/pull/88

**Comment by Luis-GA** [comment]
PR here https://github.com/hyperledger/aries-cloudagent-python/pull/1186

**Comment by dbluhm** [comment]
We had some flaws in our understanding of the problem for the PR opened against Hyperledger main. Let's discuss this some more and figure out what we can do to overcome this.

**Comment by dbluhm** [comment]
Removing from radar due to not being a priority at this time.
