### ISSUE TITLE
Story: Select resolvers by regular expression or string prefix

### ISSUE THREAD

**Issue by dbluhm** [sicpa-dlab/aries-cloudagent-python#65]
Right now, resolvers are selected by the core resolver based on matching to the DID method i.e. `key` in `did:key:z6...` or `sov` in `did:sov:abc123`. By instead using a regular expression or a string prefix, we can make more specific resolvers.

For example, `did:key` uses multi-base and multi-codec to encode keys of different types. Using a string prefix `did:key:z6` as the matcher means we can have a `did:key` resolver for just ed25519 keys. This also means we won't get false positives when selecting a resolver such as when a `did:key:zru...` (which is a secp256 key) is being matched to a resolver but our `key` method resolver only supports ed25519.

As another example, consider the Indy DID method which defines that a DID on Sovrin staging net would look like:
`did:indy:sovrin:staging:6cgbu8ZPoWTnR5Rv5JcSMB`. By using a regular expression or string prefix, we can have separate resolvers for `did:indy:sovrin`, `did:indy:sovrin:staging`, `did:indy:idunion`, etc. etc..

This will impact the DIDComm resolver plugin's model for being selected and it's own connection selection for resolution. It might be favorable to make the DID string to entity selection reusable and fast so the DIDComm resolver can reuse it to select connections to ask.

**Comment by Luis-GA** [comment]
I have been thinking about it. And I guess the best option would be start from the most restrictive "method:networks" to the simpler one, just the method.

For instance:
You have the following resolvers methods: 

- indy:sovrin
- indy:sovrin:staging
- indy:idunion

And the following did:
`did:indy:sovrin:staging:v1:6cgbu8ZPoWTnR5Rv5JcSMB`

In the first iteration, the comparation with the resolvers methods will be the more restrive: `"indy:sovrin:staging:v1"`. Lets start with the comparation:
"indy:sovrin:staging:v1" != indy:sovrin
"indy:sovrin:staging:v1" != indy:sovrin:staging
"indy:sovrin:staging:v1" != indy:idunion

We have not reach any match. So we could decrece the method to `"indy:sovrin:staging"` The comparation will be the following:
"indy:sovrin:staging:v1" != indy:sovrin
"indy:sovrin:staging:v1" = indy:sovrin:staging
"indy:sovrin:staging:v1" != indy:idunion

Now we have found a match so it is possible to resolve the did "did:indy:sovrin:staging:v1:6cgbu8ZPoWTnR5Rv5JcSMB" with the resolver that has the method "indy:sovrin:staging".

**Comment by dbluhm** [comment]
I think we can keep this simple and just say that a resolver defines a regular expression like `did:indy:sovrin:.*` and then the resolver would be responsible for further processing to pick the sub-network. Or, a resolver that only handles sovrin staging would define the regular expression `did:indy:sovrin:staging:.*`. So it's not just the method or network that we match on, but the entire DID.

**Comment by Luis-GA** [comment]
[PR: 73](https://github.com/sicpa-dlab/aries-cloudagent-python/pull/73)

**Comment by Luis-GA** [comment]
I am going to comment your message focusing in the bold text:
> I think we can keep this simple and just say that a resolver defines a regular expression like `did:indy:sovrin:.*` and then the resolver would be responsible for further processing to pick the sub-network. **Or, a resolver that only handles sovrin staging would define the regular expression `did:indy:sovrin:staging:.*`. So it's not just the method or network that we match on, but the entire DID.**

Probably the way to resolve the did based on the network could be managed by the resolver itself. Each resolver could know their ways to represent the network and if they are ready to resolve and how to do it in a properly way.
