### ISSUE TITLE
Task: Audit log/resolution metadata in resolution result

### ISSUE THREAD

**Issue by dbluhm** [sicpa-dlab/aries-cloudagent-python#77]
As an ACA-Py User, when resolving a DID Document, I want to know whether the DID Document or other resource (dereferenced object) was resolved through a native or non-native resolver and other resolution metadata.

As an example of what some of this data may include, see the DID Spec's Resolution metadata section and what the uniresolver returns in addition to the DID Document.

**Comment by Luis-GA** [comment]
Taking into account the spec: https://github.com/hyperledger/aries-rfcs/blob/82ace6001f97552f05d3da5472bcf9dbf7726a05/features/0124-did-resolution-protocol/README.md


There are required changes on aca-py to allow the generation of resolution metadata with the resolution information. 
https://github.com/sicpa-dlab/aries-cloudagent-python/pull/81

Once propagated the resolution information, the plugin can generate logs with the retrieved information.

**Comment by dbluhm** [comment]
To put a thought out there, the universal resolver returns a "DID resolution result" object. What do you think of a similar approach for this? It means a little more unpacking than just a tuple return but it could be good to have the added flexibility of adding values without changing the method signature in the future if needed. Thoughts?
