### ISSUE TITLE
Task: Relative DID URL support

### ISSUE THREAD

**Issue by dbluhm** [sicpa-dlab/aries-cloudagent-python#78]
In DID Documents, it is valid for a DID URL to omit the DID when referencing another part of the same document.

For example:
```
{
    "@context": "...",
    "id": "did:example:123",
    "verificationMethod": [
        {
            "id": "#key-1",
            ...
        }
    ],
    "authentication": [
        "#key-1"
    ]
}
```

**Comment by Luis-GA** [comment]
With the last version of pydid. replicating your example:
```
{
    "@context": "https://w3id.org/did/v1",
    "id": "did:example:123",
    "verificationMethod": [
        {
            "id": "#key-1",
            "type": "EcdsaSecp256k1VerificationKey2019",
            "publicKeyBase58": "020a5"
        }
    ],
    "authentication": [
        "#key-1"
    ]
}
```
It founds error due:

- DID could not be parsed from URL #key-1 for dictionary value @ data['verificationMethod'][0]['id']
- pydid.doc.verification_method.VerificationMethodValidationError: Failed to validate verification method: expected a dictionary (However if the id is complete as  "did:example:123#key-1", it is validated properly)

The most clear example that pydid validates properly:

```
{
    "@context": "https://w3id.org/did/v1",
    "id": "did:example:123",
    "verificationMethod": [
        {
            "id": "did:key:test#key-1",
            "type": "EcdsaSecp256k1VerificationKey2019",
            "publicKeyBase58": "020a5"
        }
    ],
    "authentication": [
        "did:key:test#key-1"
    ]
}
```

**Comment by Luis-GA** [comment]
I have not clear if it is a task for aries-cloudagent-python or for the py-did
