### ISSUE TITLE
Task: Document DID Resolver

### ISSUE THREAD

**Issue by dbluhm** [sicpa-dlab/aries-cloudagent-python#82]
We've landed DID Resolver support in ACA-Py -- now we need to document it.

- Usage
  - In ACA-Py (through resolver interface)
  - From controller
- Writing a resolver plugin
- General architecture diagrams (for internal use)

**Comment by Luis-GA** [comment]
Open document: https://hackmd.io/@N4ajEU3RSU6dWTN4yKDSjw/rJj3b4gdO/edit

**Comment by burdettadam** [comment]
I think this is ready to be marked as done. Did we want to make a pr to main with this as a md file?

**Comment by dbluhm** [comment]
Not done until we have a merged PR 🙂

**Comment by dbluhm** [comment]
PR opened: https://github.com/hyperledger/aries-cloudagent-python/pull/1229

@victormartinez-work you mentioned having planned edits for the document but I didn't spot those anywhere. The basically copied directly from the original HackMD document above if you still would like to make edits there and I can add them to the PR.

**Comment by victormartinez-work** [comment]
> PR opened: [hyperledger#1229](https://github.com/hyperledger/aries-cloudagent-python/pull/1229)
> 
> @victormartinez-work you mentioned having planned edits for the document but I didn't spot those anywhere. I basically copied directly from the original HackMD document above if you still would like to make edits there and I can add them to the PR.

I added a section in the essif-lab project about our did universal resolution work base on your yours and Lui documentation. You can not see it because is hosted in another repo .... but the documentation you added in aca-py is excellent. Let's keep it this way.
